// Nội dung học chi tiết — học theo CỤM (chunk) + câu mẫu, không học từ lẻ.
// Mỗi cụm có thể đẩy thẳng vào hệ thống ôn tập SRS.

import { IPA_SOUNDS, MINIMAL_PAIRS } from "@/data/ipa";

export type LessonPhrase = {
  en: string; // cụm/câu cần nói được
  vi: string; // nghĩa tiếng Việt
  ipa?: string; // phiên âm gợi ý
  example: string; // câu mẫu dùng cụm này
};

export type LessonContent = {
  slug: string;
  title: string;
  cefr: string;
  intro: string; // mục tiêu ngắn của bài
  tip?: string; // mẹo luyện
  phrases: LessonPhrase[];
  // (Tùy chọn) ID video YouTube để nhúng phần luyện nghe. Bỏ trống → hiện link
  // tìm kiếm theo kênh uy tín hợp cấp độ (xem src/lib/listening.ts).
  youtubeId?: string;
};

// Bài IPA dùng CHUNG nguồn dữ liệu với trang /ipa (src/data/ipa.ts) — sửa 1 nơi, cả hai cập nhật.
function ipaSoundPhrases(): LessonPhrase[] {
  const sounds: LessonPhrase[] = IPA_SOUNDS.map((s) => ({
    en: `${s.symbol} — ${s.words.slice(0, 2).join(", ")}`,
    vi: (s.hard ? "⚠️ Khó với người Việt. " : "") + s.tip,
    ipa: s.symbol,
    example: s.example,
  }));
  const pairs: LessonPhrase[] = MINIMAL_PAIRS.map((p) => ({
    en: `${p.a.word} ↔ ${p.b.word} (${p.sound})`,
    vi: p.tip,
    ipa: `${p.a.ipa} ↔ ${p.b.ipa}`,
    example: p.example,
  }));
  return [...sounds, ...pairs];
}

export const lessonContent: Record<string, LessonContent> = {
  greetings: {
    slug: "greetings",
    title: "Chào hỏi & giới thiệu",
    cefr: "A1",
    intro:
      "Nói được những câu mở đầu hội thoại và tự giới thiệu bản thân một cách tự nhiên.",
    tip: "Đừng dịch từng từ. Học nguyên cụm và bật ra cả khối khi cần.",
    phrases: [
      {
        en: "Nice to meet you.",
        vi: "Rất vui được gặp bạn.",
        ipa: "/naɪs tə ˈmiːt juː/",
        example: "Hi, I'm Nam. Nice to meet you.",
      },
      {
        en: "My name is…",
        vi: "Tên tôi là…",
        ipa: "/maɪ ˈneɪm ɪz/",
        example: "My name is Linh, and I'm from Hanoi.",
      },
      {
        en: "I'm from…",
        vi: "Tôi đến từ…",
        ipa: "/aɪm frɒm/",
        example: "I'm from Vietnam.",
      },
      {
        en: "How are you doing?",
        vi: "Dạo này bạn thế nào?",
        ipa: "/haʊ ɑːr juː ˈduːɪŋ/",
        example: "Hey! How are you doing today?",
      },
      {
        en: "What do you do?",
        vi: "Bạn làm nghề gì?",
        ipa: "/wɒt də juː duː/",
        example: "Nice to meet you. So, what do you do?",
      },
      {
        en: "See you later.",
        vi: "Hẹn gặp lại.",
        ipa: "/siː juː ˈleɪtər/",
        example: "I have to go now. See you later!",
      },
      {
        en: "How's it going?",
        vi: "Dạo này sao rồi?",
        ipa: "/haʊz ɪt ˈɡəʊɪŋ/",
        example: "Hi Mai, how's it going?",
      },
      {
        en: "Long time no see!",
        vi: "Lâu quá không gặp!",
        ipa: "/lɒŋ taɪm nəʊ siː/",
        example: "Hey, long time no see! How have you been?",
      },
      {
        en: "Let me introduce myself.",
        vi: "Để tôi tự giới thiệu.",
        ipa: "/lɛt miː ˌɪntrəˈdjuːs maɪˈsɛlf/",
        example: "Let me introduce myself. I'm Nam.",
      },
    ],
  },
  family: {
    slug: "family",
    title: "Gia đình",
    cefr: "A1",
    intro: "Mô tả các thành viên trong gia đình và mối quan hệ.",
    tip: "Tự kể về gia đình mình 3–5 câu mỗi ngày, đọc to thành tiếng.",
    phrases: [
      {
        en: "There are … people in my family.",
        vi: "Gia đình tôi có … người.",
        ipa: "/ðeər ɑːr/",
        example: "There are four people in my family.",
      },
      {
        en: "I have an older brother.",
        vi: "Tôi có một anh trai.",
        ipa: "/aɪ hæv ən ˈəʊldər ˈbrʌðər/",
        example: "I have an older brother and a younger sister.",
      },
      {
        en: "He takes after my dad.",
        vi: "Anh ấy giống bố tôi.",
        ipa: "/hiː ˈteɪks ˈɑːftər/",
        example: "He takes after my dad — they both love football.",
      },
      {
        en: "We get along well.",
        vi: "Chúng tôi hợp nhau.",
        ipa: "/wiː ɡɛt əˈlɒŋ wɛl/",
        example: "My sister and I get along well.",
      },
      {
        en: "She works as a…",
        vi: "Cô ấy làm nghề…",
        ipa: "/ʃiː ˈwɜːks æz/",
        example: "My mom works as a teacher.",
      },
      {
        en: "We are very close.",
        vi: "Chúng tôi rất thân nhau.",
        ipa: "/wiː ɑːr ˈvɛri kləʊs/",
        example: "I have one sister and we are very close.",
      },
      {
        en: "My parents live in …",
        vi: "Bố mẹ tôi sống ở …",
        ipa: "/maɪ ˈpeərənts lɪv ɪn/",
        example: "My parents live in the countryside.",
      },
      {
        en: "He looks like my mother.",
        vi: "Anh ấy trông giống mẹ tôi.",
        ipa: "/hiː lʊks laɪk/",
        example: "My brother looks like my mother.",
      },
    ],
  },
  "numbers-time": {
    slug: "numbers-time",
    title: "Số đếm & thời gian",
    cefr: "A1",
    intro: "Nói giờ giấc, ngày tháng và các con số trong đời sống.",
    tip: "Đọc to mọi con số bạn nhìn thấy trong ngày (giá tiền, giờ, biển số).",
    phrases: [
      {
        en: "What time is it?",
        vi: "Mấy giờ rồi?",
        ipa: "/wɒt taɪm ɪz ɪt/",
        example: "Excuse me, what time is it?",
      },
      {
        en: "It's half past seven.",
        vi: "Bây giờ là 7 giờ rưỡi.",
        ipa: "/ɪts hɑːf pɑːst ˈsɛvən/",
        example: "It's half past seven, let's go.",
      },
      {
        en: "a quarter to nine",
        vi: "9 giờ kém 15",
        ipa: "/ə ˈkwɔːtər tə naɪn/",
        example: "The meeting starts at a quarter to nine.",
      },
      {
        en: "How much is it?",
        vi: "Cái này giá bao nhiêu?",
        ipa: "/haʊ mʌtʃ ɪz ɪt/",
        example: "This looks nice. How much is it?",
      },
      {
        en: "on the first of May",
        vi: "vào ngày 1 tháng 5",
        ipa: "/ɒn ðə fɜːst əv meɪ/",
        example: "My birthday is on the first of May.",
      },
      {
        en: "It's a quarter past ten.",
        vi: "Bây giờ là 10 giờ 15.",
        ipa: "/ɪts ə ˈkwɔːtər pɑːst tɛn/",
        example: "Hurry up, it's a quarter past ten.",
      },
      {
        en: "from nine to five",
        vi: "từ 9 giờ đến 5 giờ",
        ipa: "/frɒm naɪn tə faɪv/",
        example: "I work from nine to five.",
      },
      {
        en: "It costs about …",
        vi: "Cái này khoảng …",
        ipa: "/ɪt kɒsts əˈbaʊt/",
        example: "It costs about fifty thousand dong.",
      },
    ],
  },
  food: {
    slug: "food",
    title: "Đồ ăn & sở thích",
    cefr: "A1",
    intro: "Gọi món, nói về món ăn yêu thích và sở thích cá nhân.",
    tip: "Trước mỗi bữa ăn, thử mô tả món của bạn bằng 2 câu tiếng Anh.",
    phrases: [
      {
        en: "I'd like…",
        vi: "Tôi muốn… (lịch sự)",
        ipa: "/aɪd laɪk/",
        example: "I'd like a coffee, please.",
      },
      {
        en: "I'm really into…",
        vi: "Tôi rất mê…",
        ipa: "/aɪm ˈrɪəli ˈɪntə/",
        example: "I'm really into spicy food.",
      },
      {
        en: "I'm not a big fan of…",
        vi: "Tôi không thích lắm…",
        ipa: "/aɪm nɒt ə bɪɡ fæn əv/",
        example: "I'm not a big fan of seafood.",
      },
      {
        en: "Could I have the bill, please?",
        vi: "Cho tôi xin hoá đơn nhé?",
        ipa: "/kʊd aɪ hæv ðə bɪl/",
        example: "That was delicious. Could I have the bill, please?",
      },
      {
        en: "It tastes great.",
        vi: "Món này ngon thật.",
        ipa: "/ɪt ˈteɪsts ɡreɪt/",
        example: "Try this — it tastes great!",
      },
      {
        en: "Are you ready to order?",
        vi: "Bạn gọi món chưa?",
        ipa: "/ɑːr juː ˈrɛdi tu ˈɔːdər/",
        example: "Good evening. Are you ready to order?",
      },
      {
        en: "I'm starving.",
        vi: "Tôi đói lả rồi.",
        ipa: "/aɪm ˈstɑːvɪŋ/",
        example: "Let's eat — I'm starving!",
      },
      {
        en: "Could you pass me the …?",
        vi: "Bạn đưa giúp tôi … nhé?",
        ipa: "/kʊd juː pɑːs miː/",
        example: "Could you pass me the salt, please?",
      },
    ],
  },
  "ipa-sounds": {
    slug: "ipa-sounds",
    title: "Âm IPA cơ bản",
    cefr: "A1",
    intro:
      "Trọn bộ 44 âm tiếng Anh (chuẩn IPA): 24 phụ âm + 20 nguyên âm (12 đơn + 8 đôi). Học theo phương pháp đã được kiểm chứng: NGHE → NHẠI LẠI (shadowing) → luyện CẶP ÂM dễ nhầm để tai phân biệt rõ rồi miệng mới nói đúng.",
    tip: "Quy trình mỗi ngày: ① Bấm 🔊 nghe mẫu, NHẠI LẠI NGAY theo nhịp (shadowing) — phóng đại khẩu hình lúc đầu. ② Đọc IPA chậm, tách từng âm. ③ Chỉ luyện kỹ 3–5 âm/ngày và lặp đều, đừng cố nuốt cả 44 âm một lúc. ④ Làm kỹ phần 'Cặp âm dễ nhầm' ở cuối bài. ⑤ Muốn ghi âm & chấm điểm so với mẫu → sang mục Shadowing.",
    phrases: ipaSoundPhrases(),
  },
  "describe-compare": {
    slug: "describe-compare",
    title: "Miêu tả & so sánh",
    cefr: "A1 Movers",
    intro:
      "So sánh người, vật, con vật bằng so sánh hơn và so sánh nhất — kỹ năng cốt lõi của A1 Movers.",
    tip: "Tính từ ngắn thêm -er/-est; tính từ dài dùng more/the most. Tập so sánh 2 đồ vật quanh bạn.",
    phrases: [
      {
        en: "… is bigger than …",
        vi: "… to hơn …",
        ipa: "/ˈbɪɡər ðæn/",
        example: "An elephant is bigger than a horse.",
      },
      {
        en: "the tallest in …",
        vi: "cao nhất trong …",
        ipa: "/ðə ˈtɔːlɪst/",
        example: "He is the tallest boy in my class.",
      },
      {
        en: "more beautiful than …",
        vi: "đẹp hơn …",
        ipa: "/mɔːr ˈbjuːtɪfəl/",
        example: "This flower is more beautiful than that one.",
      },
      {
        en: "It looks like …",
        vi: "Trông giống như …",
        ipa: "/ɪt lʊks laɪk/",
        example: "That cloud looks like a rabbit.",
      },
      {
        en: "as … as …",
        vi: "… bằng/ngang …",
        ipa: "/æz … æz/",
        example: "My bag is as heavy as yours.",
      },
      {
        en: "better than …",
        vi: "tốt hơn … (so sánh bất quy tắc)",
        ipa: "/ˈbɛtər ðæn/",
        example: "This phone is better than my old one.",
      },
      {
        en: "the most … in the world",
        vi: "… nhất thế giới",
        ipa: "/ðə məʊst/",
        example: "It is the most expensive car in the world.",
      },
      {
        en: "the same as …",
        vi: "giống hệt như …",
        ipa: "/ðə seɪm æz/",
        example: "My shoes are the same as yours.",
      },
    ],
  },
  "daily-routine": {
    slug: "daily-routine",
    title: "Thói quen (hiện tại đơn)",
    cefr: "A1 Movers",
    intro:
      "Kể về một ngày của bạn bằng thì hiện tại đơn và trạng từ chỉ tần suất.",
    tip: "Ngôi he/she/it nhớ thêm -s. Tập kể lịch trình hằng ngày của bạn thành tiếng.",
    phrases: [
      {
        en: "I usually get up at …",
        vi: "Tôi thường thức dậy lúc …",
        ipa: "/ˈjuːʒuəli ɡɛt ʌp/",
        example: "I usually get up at six o'clock.",
      },
      {
        en: "She goes to work by …",
        vi: "Cô ấy đi làm bằng …",
        ipa: "/ɡəʊz tə wɜːk baɪ/",
        example: "She goes to work by bus.",
      },
      {
        en: "He never eats …",
        vi: "Anh ấy không bao giờ ăn …",
        ipa: "/ˈnɛvər iːts/",
        example: "He never eats breakfast in the morning.",
      },
      {
        en: "What time do you …?",
        vi: "Bạn … lúc mấy giờ?",
        ipa: "/wɒt taɪm də juː/",
        example: "What time do you go to bed?",
      },
      {
        en: "every day / on Sundays",
        vi: "mỗi ngày / vào Chủ nhật",
        ipa: "/ˈɛvri deɪ/",
        example: "We play football on Sundays.",
      },
      {
        en: "After that, I …",
        vi: "Sau đó, tôi …",
        ipa: "/ˈɑːftər ðæt/",
        example: "I have breakfast. After that, I go to school.",
      },
      {
        en: "He doesn't … on weekdays",
        vi: "Anh ấy không … vào ngày thường",
        ipa: "/hiː ˈdʌznt/",
        example: "He doesn't work on weekdays.",
      },
      {
        en: "How often do you …?",
        vi: "Bạn … bao lâu một lần?",
        ipa: "/haʊ ˈɒfən də juː/",
        example: "How often do you go to the gym?",
      },
    ],
  },
  "past-simple": {
    slug: "past-simple",
    title: "Kể chuyện quá khứ",
    cefr: "A1 Movers",
    intro:
      "Kể lại việc đã xảy ra bằng quá khứ đơn — cả động từ có quy tắc và bất quy tắc.",
    tip: "Học cặp present→past của động từ bất quy tắc (go→went, eat→ate). Kể lại hôm qua của bạn.",
    phrases: [
      {
        en: "Yesterday I went to …",
        vi: "Hôm qua tôi đã đi …",
        ipa: "/ˈjɛstədeɪ aɪ wɛnt/",
        example: "Yesterday I went to the park with my friends.",
      },
      {
        en: "We watched … last night",
        vi: "Tối qua chúng tôi đã xem …",
        ipa: "/wɒtʃt/",
        example: "We watched a film last night.",
      },
      {
        en: "Did you … ?",
        vi: "Bạn đã … chưa?",
        ipa: "/dɪd juː/",
        example: "Did you finish your homework?",
      },
      {
        en: "I didn't …",
        vi: "Tôi đã không …",
        ipa: "/aɪ ˈdɪdnt/",
        example: "I didn't see her at the party.",
      },
      {
        en: "It was … / They were …",
        vi: "Nó đã … / Chúng đã …",
        ipa: "/ɪt wɒz/",
        example: "The food was delicious and the people were kind.",
      },
      {
        en: "Then we decided to …",
        vi: "Rồi chúng tôi quyết định …",
        ipa: "/ðɛn wiː dɪˈsaɪdɪd tə/",
        example: "It started to rain, then we decided to go home.",
      },
      {
        en: "When I was young, I …",
        vi: "Hồi nhỏ, tôi …",
        ipa: "/wɛn aɪ wɒz jʌŋ/",
        example: "When I was young, I lived by the sea.",
      },
      {
        en: "How was your …?",
        vi: "… của bạn thế nào?",
        ipa: "/haʊ wɒz jɔː/",
        example: "Hi! How was your weekend?",
      },
    ],
  },
  "places-directions": {
    slug: "places-directions",
    title: "Nơi chốn & chỉ đường",
    cefr: "A1 Movers",
    intro:
      "Hỏi và chỉ đường, nói về địa điểm và phương tiện đi lại bằng giới từ chỉ nơi chốn.",
    tip: "Tập mô tả đường từ nhà bạn tới một nơi quen thuộc bằng tiếng Anh.",
    phrases: [
      {
        en: "How do I get to …?",
        vi: "Làm sao để tới …?",
        ipa: "/haʊ də aɪ ɡɛt tə/",
        example: "Excuse me, how do I get to the station?",
      },
      {
        en: "Go straight on / Turn left",
        vi: "Đi thẳng / Rẽ trái",
        ipa: "/ɡəʊ streɪt ɒn/",
        example: "Go straight on and then turn left.",
      },
      {
        en: "It's next to / opposite …",
        vi: "Nó ở cạnh / đối diện …",
        ipa: "/nɛkst tə/",
        example: "The bank is next to the supermarket.",
      },
      {
        en: "between … and …",
        vi: "giữa … và …",
        ipa: "/bɪˈtwiːn/",
        example: "The school is between the park and the library.",
      },
      {
        en: "I'm going there by …",
        vi: "Tôi tới đó bằng …",
        ipa: "/baɪ/",
        example: "I'm going there by train.",
      },
      {
        en: "Is there a … near here?",
        vi: "Gần đây có … không?",
        ipa: "/ɪz ðeər ə … nɪə hɪə/",
        example: "Excuse me, is there a pharmacy near here?",
      },
      {
        en: "at the corner of …",
        vi: "ở góc …",
        ipa: "/æt ðə ˈkɔːnər əv/",
        example: "The café is at the corner of the street.",
      },
      {
        en: "It's a five-minute walk.",
        vi: "Đi bộ năm phút là tới.",
        ipa: "/ɪts ə faɪv ˈmɪnɪt wɔːk/",
        example: "Don't worry, it's a five-minute walk.",
      },
    ],
  },
  "health-body": {
    slug: "health-body",
    title: "Sức khoẻ & cơ thể",
    cefr: "A1 Movers",
    intro:
      "Nói về cơ thể, cảm giác không khoẻ và lời khuyên cơ bản (must / have to).",
    tip: "Khi thấy mệt, thử nói cảm giác của bạn bằng tiếng Anh trước.",
    phrases: [
      {
        en: "I've got a …ache",
        vi: "Tôi bị đau … (đầu/răng/bụng)",
        ipa: "/aɪv ɡɒt ə/",
        example: "I've got a headache today.",
      },
      {
        en: "I don't feel well.",
        vi: "Tôi thấy không khoẻ.",
        ipa: "/aɪ dəʊnt fiːl wɛl/",
        example: "I can't go to school — I don't feel well.",
      },
      {
        en: "You must see a doctor.",
        vi: "Bạn phải đi khám bác sĩ.",
        ipa: "/juː mʌst siː ə ˈdɒktər/",
        example: "If it hurts, you must see a doctor.",
      },
      {
        en: "You have to rest.",
        vi: "Bạn cần phải nghỉ ngơi.",
        ipa: "/juː hæv tə rɛst/",
        example: "You have to rest and drink water.",
      },
      {
        en: "Take care of yourself.",
        vi: "Giữ gìn sức khoẻ nhé.",
        ipa: "/teɪk keər əv jɔːˈsɛlf/",
        example: "Get well soon and take care of yourself.",
      },
      {
        en: "My … hurts.",
        vi: "… của tôi bị đau.",
        ipa: "/hɜːts/",
        example: "I can't run because my leg hurts.",
      },
      {
        en: "You should drink more water.",
        vi: "Bạn nên uống nhiều nước hơn.",
        ipa: "/juː ʃʊd drɪŋk/",
        example: "You look tired. You should drink more water.",
      },
      {
        en: "I feel much better now.",
        vi: "Tôi thấy đỡ hơn nhiều rồi.",
        ipa: "/aɪ fiːl mʌtʃ ˈbɛtər/",
        example: "Thanks for asking — I feel much better now.",
      },
    ],
  },
  "free-time": {
    slug: "free-time",
    title: "Sở thích & thể thao",
    cefr: "A1 Movers",
    intro:
      "Nói về sở thích, rủ rê và đề nghị (want to / shall / could) — chủ đề Sports & leisure của Movers.",
    tip: "Dùng verb+ing để nói sở thích: I like swimming. Rủ bạn bằng 'Shall we…?'.",
    phrases: [
      {
        en: "I'm good at …ing",
        vi: "Tôi giỏi (làm) …",
        ipa: "/aɪm ɡʊd æt/",
        example: "I'm good at swimming.",
      },
      {
        en: "I want to learn …",
        vi: "Tôi muốn học …",
        ipa: "/aɪ wɒnt tə lɜːn/",
        example: "I want to learn how to skate.",
      },
      {
        en: "Shall we …?",
        vi: "Chúng ta … nhé?",
        ipa: "/ʃæl wiː/",
        example: "Shall we play badminton this afternoon?",
      },
      {
        en: "Would you like to …?",
        vi: "Bạn có muốn … không?",
        ipa: "/wʊd juː laɪk tə/",
        example: "Would you like to come to my house?",
      },
      {
        en: "I could … when I was …",
        vi: "Tôi đã có thể … khi tôi …",
        ipa: "/aɪ kʊd/",
        example: "I could ride a bike when I was six.",
      },
      {
        en: "In my free time, I …",
        vi: "Lúc rảnh, tôi …",
        ipa: "/ɪn maɪ friː taɪm/",
        example: "In my free time, I read comics.",
      },
      {
        en: "Why don't we …?",
        vi: "Sao chúng ta không …?",
        ipa: "/waɪ dəʊnt wiː/",
        example: "Why don't we go to the cinema tonight?",
      },
      {
        en: "I'm not very keen on …",
        vi: "Tôi không thích … lắm.",
        ipa: "/aɪm nɒt ˈvɛri kiːn ɒn/",
        example: "I'm not very keen on running.",
      },
    ],
  },
  "present-continuous": {
    slug: "present-continuous",
    title: "Đang xảy ra (tiếp diễn)",
    cefr: "A2 Flyers",
    intro:
      "Mô tả việc đang diễn ra ngay lúc nói bằng thì hiện tại tiếp diễn — kỹ năng tả tranh cốt lõi của Flyers.",
    tip: "Công thức am/is/are + V-ing. Nhìn quanh phòng và tả 3 việc người ta đang làm.",
    phrases: [
      {
        en: "I'm …ing right now.",
        vi: "Tôi đang … ngay bây giờ.",
        ipa: "/aɪm … ɪŋ/",
        example: "I'm cooking dinner right now.",
      },
      {
        en: "She is wearing …",
        vi: "Cô ấy đang mặc …",
        ipa: "/ʃiː ɪz ˈweərɪŋ/",
        example: "She is wearing a red dress today.",
      },
      {
        en: "They are playing …",
        vi: "Họ đang chơi …",
        ipa: "/ðeɪ ɑːr ˈpleɪɪŋ/",
        example: "Look! They are playing in the garden.",
      },
      {
        en: "What are you doing?",
        vi: "Bạn đang làm gì vậy?",
        ipa: "/wɒt ɑːr juː ˈduːɪŋ/",
        example: "Hi! What are you doing at the moment?",
      },
      {
        en: "It isn't raining now.",
        vi: "Bây giờ trời không mưa.",
        ipa: "/ɪt ˈɪznt ˈreɪnɪŋ/",
        example: "We can go out — it isn't raining now.",
      },
      {
        en: "We are having dinner.",
        vi: "Chúng tôi đang ăn tối.",
        ipa: "/wiː ɑːr ˈhævɪŋ ˈdɪnər/",
        example: "We are having dinner — can I call you back?",
      },
      {
        en: "Why is he crying?",
        vi: "Sao anh ấy đang khóc vậy?",
        ipa: "/waɪ ɪz hiː ˈkraɪɪŋ/",
        example: "Why is he crying? Is he okay?",
      },
      {
        en: "I'm not feeling well today.",
        vi: "Hôm nay tôi thấy không khoẻ.",
        ipa: "/aɪm nɒt ˈfiːlɪŋ wɛl/",
        example: "I'm staying home — I'm not feeling well today.",
      },
    ],
  },
  "future-plans": {
    slug: "future-plans",
    title: "Kế hoạch & dự định",
    cefr: "A2 Flyers",
    intro:
      "Nói về dự định và dự đoán tương lai bằng 'going to' và 'will'.",
    tip: "'going to' cho kế hoạch đã định; 'will' cho quyết định tức thì và dự đoán. Tập kể kế hoạch cuối tuần.",
    phrases: [
      {
        en: "I'm going to …",
        vi: "Tôi định sẽ …",
        ipa: "/aɪm ˈɡəʊɪŋ tə/",
        example: "I'm going to visit my grandma this weekend.",
      },
      {
        en: "We're going to …",
        vi: "Chúng tôi sẽ … (kế hoạch)",
        ipa: "/wɪər ˈɡəʊɪŋ tə/",
        example: "We're going to have a party on Saturday.",
      },
      {
        en: "I think it will …",
        vi: "Tôi nghĩ trời/nó sẽ …",
        ipa: "/aɪ θɪŋk ɪt wɪl/",
        example: "I think it will rain later.",
      },
      {
        en: "I'll help you.",
        vi: "Tôi sẽ giúp bạn. (quyết định ngay)",
        ipa: "/aɪl hɛlp juː/",
        example: "Don't worry, I'll help you with that.",
      },
      {
        en: "What are you going to do …?",
        vi: "Bạn định làm gì …?",
        ipa: "/wɒt ɑːr juː ˈɡəʊɪŋ tə duː/",
        example: "What are you going to do after school?",
      },
      {
        en: "She's going to study abroad.",
        vi: "Cô ấy sẽ đi du học.",
        ipa: "/ʃiːz ˈɡəʊɪŋ tə ˈstʌdi əˈbrɔːd/",
        example: "Next year she's going to study abroad.",
      },
      {
        en: "It won't be easy.",
        vi: "Việc đó sẽ không dễ đâu.",
        ipa: "/ɪt wəʊnt biː ˈiːzi/",
        example: "It won't be easy, but I'll try my best.",
      },
      {
        en: "Maybe I'll …",
        vi: "Có lẽ tôi sẽ …",
        ipa: "/ˈmeɪbiː aɪl/",
        example: "Maybe I'll travel somewhere this summer.",
      },
    ],
  },
  "present-perfect": {
    slug: "present-perfect",
    title: "Đã từng làm",
    cefr: "A2 Flyers",
    intro:
      "Nói về trải nghiệm và việc vừa hoàn thành bằng hiện tại hoàn thành (have/has + V3).",
    tip: "Dùng ever/never cho trải nghiệm, just/already/yet cho việc gần đây. Hỏi bạn 'Have you ever…?'.",
    phrases: [
      {
        en: "Have you ever …?",
        vi: "Bạn đã bao giờ … chưa?",
        ipa: "/hæv juː ˈɛvər/",
        example: "Have you ever been to Da Nang?",
      },
      {
        en: "I've never …",
        vi: "Tôi chưa bao giờ …",
        ipa: "/aɪv ˈnɛvər/",
        example: "I've never tried surfing before.",
      },
      {
        en: "I've just …",
        vi: "Tôi vừa mới …",
        ipa: "/aɪv dʒʌst/",
        example: "I've just finished my homework.",
      },
      {
        en: "She has already …",
        vi: "Cô ấy đã … rồi.",
        ipa: "/ʃiː həz ɔːlˈrɛdi/",
        example: "She has already eaten lunch.",
      },
      {
        en: "I haven't … yet.",
        vi: "Tôi vẫn chưa …",
        ipa: "/aɪ ˈhævnt … jɛt/",
        example: "I haven't seen that film yet.",
      },
      {
        en: "I've been to … twice.",
        vi: "Tôi đã đến … hai lần.",
        ipa: "/aɪv biːn tə … twaɪs/",
        example: "I've been to Hue twice.",
      },
      {
        en: "Have you finished … yet?",
        vi: "Bạn làm xong … chưa?",
        ipa: "/hæv juː ˈfɪnɪʃt … jɛt/",
        example: "Have you finished your report yet?",
      },
      {
        en: "He's lost his …",
        vi: "Anh ấy làm mất … rồi.",
        ipa: "/hiːz lɒst/",
        example: "He's lost his keys, so he can't get in.",
      },
    ],
  },
  "weather-seasons": {
    slug: "weather-seasons",
    title: "Thời tiết & mùa",
    cefr: "A2 Flyers",
    intro:
      "Nói về thời tiết, mùa và dự báo — chủ đề 'The weather' của Flyers.",
    tip: "Thời tiết thường dùng 'It's …'. Mỗi sáng tả thời tiết hôm đó bằng 2 câu.",
    phrases: [
      {
        en: "What's the weather like?",
        vi: "Thời tiết thế nào?",
        ipa: "/wɒts ðə ˈwɛðər laɪk/",
        example: "What's the weather like today?",
      },
      {
        en: "It's sunny and warm.",
        vi: "Trời nắng và ấm.",
        ipa: "/ɪts ˈsʌni ænd wɔːm/",
        example: "It's sunny and warm, let's go to the beach.",
      },
      {
        en: "It's getting colder.",
        vi: "Trời đang lạnh dần.",
        ipa: "/ɪts ˈɡɛtɪŋ ˈkəʊldər/",
        example: "Take a coat — it's getting colder.",
      },
      {
        en: "In winter it often …",
        vi: "Vào mùa đông trời thường …",
        ipa: "/ɪn ˈwɪntər/",
        example: "In winter it often rains in the north.",
      },
      {
        en: "I prefer … weather.",
        vi: "Tôi thích thời tiết … hơn.",
        ipa: "/aɪ prɪˈfɜːr/",
        example: "I prefer cool weather to hot weather.",
      },
      {
        en: "It looks like rain.",
        vi: "Trông như sắp mưa.",
        ipa: "/ɪt lʊks laɪk reɪn/",
        example: "Take an umbrella — it looks like rain.",
      },
      {
        en: "The forecast says …",
        vi: "Dự báo nói rằng …",
        ipa: "/ðə ˈfɔːkɑːst sɛz/",
        example: "The forecast says it'll be windy tomorrow.",
      },
      {
        en: "It's freezing today.",
        vi: "Hôm nay lạnh cóng.",
        ipa: "/ɪts ˈfriːzɪŋ/",
        example: "Wear a jacket — it's freezing today.",
      },
    ],
  },
  "jobs-ambitions": {
    slug: "jobs-ambitions",
    title: "Nghề nghiệp & ước mơ",
    cefr: "A2 Flyers",
    intro:
      "Nói về công việc và ước mơ tương lai bằng 'want to be' / 'would like to be'.",
    tip: "Tập trả lời 'What do you want to be?' và giải thích lý do bằng 'because'.",
    phrases: [
      {
        en: "I want to be a …",
        vi: "Tôi muốn trở thành …",
        ipa: "/aɪ wɒnt tə biː ə/",
        example: "I want to be a doctor in the future.",
      },
      {
        en: "I'd like to work as …",
        vi: "Tôi muốn làm nghề …",
        ipa: "/aɪd laɪk tə wɜːk æz/",
        example: "I'd like to work as a teacher.",
      },
      {
        en: "A … helps people by …ing",
        vi: "Một … giúp mọi người bằng cách …",
        ipa: "/hɛlps ˈpiːpl baɪ/",
        example: "A nurse helps people by taking care of them.",
      },
      {
        en: "because I'm good at …",
        vi: "vì tôi giỏi …",
        ipa: "/bɪˈkɒz aɪm ɡʊd æt/",
        example: "I want to be an engineer because I'm good at maths.",
      },
      {
        en: "My dream job is …",
        vi: "Công việc mơ ước của tôi là …",
        ipa: "/maɪ driːm dʒɒb ɪz/",
        example: "My dream job is being a pilot.",
      },
      {
        en: "I'm interested in …",
        vi: "Tôi quan tâm đến …",
        ipa: "/aɪm ˈɪntrəstɪd ɪn/",
        example: "I'm interested in working with computers.",
      },
      {
        en: "It's a hard but rewarding job.",
        vi: "Đó là công việc vất vả nhưng xứng đáng.",
        ipa: "/hɑːd bʌt rɪˈwɔːdɪŋ/",
        example: "Teaching is a hard but rewarding job.",
      },
      {
        en: "When I grow up, I want to …",
        vi: "Khi lớn lên, tôi muốn …",
        ipa: "/wɛn aɪ ɡrəʊ ʌp/",
        example: "When I grow up, I want to help other people.",
      },
    ],
  },
  "adverbs-manner": {
    slug: "adverbs-manner",
    title: "Trạng từ chỉ cách thức",
    cefr: "A2 Flyers",
    intro:
      "Mô tả cách làm một việc bằng trạng từ (thường thêm -ly) và so sánh cách làm.",
    tip: "Tính từ → trạng từ: quick → quickly, careful → carefully. Lưu ý bất quy tắc: good → well, fast → fast.",
    phrases: [
      {
        en: "He runs quickly.",
        vi: "Anh ấy chạy nhanh.",
        ipa: "/hiː rʌnz ˈkwɪkli/",
        example: "He runs quickly and never gets tired.",
      },
      {
        en: "Please speak slowly.",
        vi: "Làm ơn nói chậm thôi.",
        ipa: "/pliːz spiːk ˈsləʊli/",
        example: "Can you please speak slowly? I'm learning.",
      },
      {
        en: "She sings beautifully.",
        vi: "Cô ấy hát rất hay.",
        ipa: "/ʃiː sɪŋz ˈbjuːtɪfli/",
        example: "She sings beautifully on the stage.",
      },
      {
        en: "I can do it well.",
        vi: "Tôi làm việc đó tốt.",
        ipa: "/aɪ kæn duː ɪt wɛl/",
        example: "I practised a lot, so now I can do it well.",
      },
      {
        en: "more carefully than …",
        vi: "cẩn thận hơn …",
        ipa: "/mɔːr ˈkeəfli ðæn/",
        example: "She works more carefully than her brother.",
      },
      {
        en: "Drive carefully!",
        vi: "Lái xe cẩn thận nhé!",
        ipa: "/draɪv ˈkeəfli/",
        example: "It's raining hard — drive carefully!",
      },
      {
        en: "She speaks English fluently.",
        vi: "Cô ấy nói tiếng Anh trôi chảy.",
        ipa: "/spiːks ˈɪŋɡlɪʃ ˈfluːəntli/",
        example: "After years of practice, she speaks English fluently.",
      },
      {
        en: "Could you say it more clearly?",
        vi: "Bạn nói rõ hơn được không?",
        ipa: "/kʊd juː seɪ ɪt mɔː ˈklɪəli/",
        example: "Sorry, could you say it more clearly?",
      },
    ],
  },
  "first-conditional": {
    slug: "first-conditional",
    title: "Câu điều kiện loại 1",
    cefr: "A2 Flyers",
    intro:
      "Nói về điều có thể xảy ra với điều kiện thật: If + hiện tại đơn, … will …",
    tip: "Mệnh đề If dùng hiện tại đơn, mệnh đề chính dùng will. Tập nói 3 câu 'If …, I will …'.",
    phrases: [
      {
        en: "If it rains, I'll …",
        vi: "Nếu trời mưa, tôi sẽ …",
        ipa: "/ɪf ɪt reɪnz/",
        example: "If it rains, I'll stay at home.",
      },
      {
        en: "If you study, you'll …",
        vi: "Nếu bạn học, bạn sẽ …",
        ipa: "/ɪf juː ˈstʌdi/",
        example: "If you study hard, you'll pass the test.",
      },
      {
        en: "I'll call you if …",
        vi: "Tôi sẽ gọi bạn nếu …",
        ipa: "/aɪl kɔːl juː ɪf/",
        example: "I'll call you if I have time.",
      },
      {
        en: "What will you do if …?",
        vi: "Bạn sẽ làm gì nếu …?",
        ipa: "/wɒt wɪl juː duː ɪf/",
        example: "What will you do if it's sunny tomorrow?",
      },
      {
        en: "Unless you hurry, …",
        vi: "Trừ khi bạn nhanh lên, …",
        ipa: "/ənˈlɛs juː ˈhʌri/",
        example: "Unless you hurry, you'll miss the bus.",
      },
      {
        en: "If I have time, I'll …",
        vi: "Nếu có thời gian, tôi sẽ …",
        ipa: "/ɪf aɪ hæv taɪm/",
        example: "If I have time, I'll help you tonight.",
      },
      {
        en: "We won't go if it rains.",
        vi: "Chúng tôi sẽ không đi nếu trời mưa.",
        ipa: "/wiː wəʊnt ɡəʊ ɪf ɪt reɪnz/",
        example: "We won't go to the park if it rains.",
      },
      {
        en: "As soon as I arrive, I'll …",
        vi: "Ngay khi tới nơi, tôi sẽ …",
        ipa: "/æz suːn æz aɪ əˈraɪv/",
        example: "As soon as I arrive, I'll text you.",
      },
    ],
  },
  restaurant: {
    slug: "restaurant",
    title: "Ở nhà hàng",
    cefr: "B1",
    intro:
      "Đặt bàn, gọi món, hỏi gợi ý và xử lý tình huống ở nhà hàng một cách lịch sự, tự nhiên.",
    tip: "Dùng câu lịch sự (Could I…? / Would you…?). Tự đóng vai bồi bàn và khách để luyện cả hai phía.",
    phrases: [
      {
        en: "I'd like to book a table for …",
        vi: "Tôi muốn đặt bàn cho … người.",
        ipa: "/aɪd laɪk tə bʊk ə ˈteɪbl/",
        example: "Hi, I'd like to book a table for two at eight.",
      },
      {
        en: "What would you recommend?",
        vi: "Bạn gợi ý món nào?",
        ipa: "/wɒt wʊd juː ˌrɛkəˈmɛnd/",
        example: "It's my first time here. What would you recommend?",
      },
      {
        en: "I'll have the …, please.",
        vi: "Cho tôi món …, làm ơn.",
        ipa: "/aɪl hæv ðə/",
        example: "I'll have the grilled chicken, please.",
      },
      {
        en: "Does this contain …?",
        vi: "Món này có … không?",
        ipa: "/dʌz ðɪs kənˈteɪn/",
        example: "Does this contain peanuts? I'm allergic.",
      },
      {
        en: "Could we get the bill, please?",
        vi: "Cho chúng tôi xin hoá đơn nhé?",
        ipa: "/kʊd wiː ɡɛt ðə bɪl/",
        example: "Everything was lovely. Could we get the bill, please?",
      },
      {
        en: "Is service included?",
        vi: "Đã bao gồm phí phục vụ chưa?",
        ipa: "/ɪz ˈsɜːvɪs ɪnˈkluːdɪd/",
        example: "Excuse me, is service included in the bill?",
      },
      {
        en: "Could we sit by the window?",
        vi: "Cho chúng tôi ngồi cạnh cửa sổ được không?",
        ipa: "/kʊd wiː sɪt baɪ ðə ˈwɪndəʊ/",
        example: "Could we sit by the window, please?",
      },
      {
        en: "I'm afraid this isn't what I ordered.",
        vi: "E là món này không phải món tôi gọi.",
        ipa: "/aɪm əˈfreɪd ðɪs ˈɪznt/",
        example: "Sorry, I'm afraid this isn't what I ordered.",
      },
      {
        en: "Can I get this to go?",
        vi: "Cho tôi gói mang về được không?",
        ipa: "/kæn aɪ ɡɛt ðɪs tə ɡəʊ/",
        example: "I'm quite full — can I get this to go?",
      },
    ],
  },
  travel: {
    slug: "travel",
    title: "Du lịch & sân bay",
    cefr: "B1",
    intro:
      "Xử lý các tình huống ở sân bay, khách sạn và khi di chuyển — hỏi đường, làm thủ tục, gặp sự cố.",
    tip: "Học theo tình huống: check-in, an ninh, nhận phòng. Tưởng tượng một chuyến đi và nói qua từng bước.",
    phrases: [
      {
        en: "I'd like to check in for my flight.",
        vi: "Tôi muốn làm thủ tục cho chuyến bay.",
        ipa: "/aɪd laɪk tə tʃɛk ɪn/",
        example: "Good morning, I'd like to check in for my flight to Tokyo.",
      },
      {
        en: "Where is the boarding gate?",
        vi: "Cửa lên máy bay ở đâu?",
        ipa: "/weər ɪz ðə ˈbɔːdɪŋ ɡeɪt/",
        example: "Excuse me, where is the boarding gate for flight VN123?",
      },
      {
        en: "I have a reservation under …",
        vi: "Tôi có đặt phòng dưới tên …",
        ipa: "/aɪ hæv ə ˌrɛzəˈveɪʃn ˈʌndər/",
        example: "Hi, I have a reservation under the name Minh.",
      },
      {
        en: "What time is check-out?",
        vi: "Mấy giờ phải trả phòng?",
        ipa: "/wɒt taɪm ɪz ˈtʃɛkaʊt/",
        example: "What time is check-out tomorrow?",
      },
      {
        en: "My luggage hasn't arrived.",
        vi: "Hành lý của tôi chưa tới.",
        ipa: "/maɪ ˈlʌɡɪdʒ ˈhæznt əˈraɪvd/",
        example: "Excuse me, my luggage hasn't arrived. What should I do?",
      },
      {
        en: "Could you tell me the way to …?",
        vi: "Bạn chỉ giúp đường tới … được không?",
        ipa: "/kʊd juː tɛl miː ðə weɪ tə/",
        example: "Could you tell me the way to the city centre?",
      },
      {
        en: "Is this seat taken?",
        vi: "Chỗ này có ai ngồi chưa?",
        ipa: "/ɪz ðɪs siːt ˈteɪkən/",
        example: "Excuse me, is this seat taken?",
      },
      {
        en: "How long does the journey take?",
        vi: "Hành trình mất bao lâu?",
        ipa: "/haʊ lɒŋ dʌz ðə ˈdʒɜːni teɪk/",
        example: "How long does the journey take by train?",
      },
      {
        en: "I'd like to extend my stay.",
        vi: "Tôi muốn ở thêm.",
        ipa: "/aɪd laɪk tə ɪkˈstɛnd maɪ steɪ/",
        example: "I'd like to extend my stay by one night.",
      },
    ],
  },
  opinions: {
    slug: "opinions",
    title: "Nêu ý kiến",
    cefr: "B1",
    intro:
      "Bày tỏ quan điểm, đồng tình hoặc phản đối lịch sự và đưa ra lý do — nền tảng cho hội thoại sâu hơn.",
    tip: "Cấu trúc: nêu ý kiến → lý do → ví dụ. Mỗi ngày chọn 1 chủ đề và nói ý kiến của bạn 30 giây.",
    phrases: [
      {
        en: "In my opinion, …",
        vi: "Theo tôi thì …",
        ipa: "/ɪn maɪ əˈpɪnjən/",
        example: "In my opinion, learning by speaking is the fastest way.",
      },
      {
        en: "I see your point, but …",
        vi: "Tôi hiểu ý bạn, nhưng …",
        ipa: "/aɪ siː jɔː pɔɪnt bʌt/",
        example: "I see your point, but I think it depends on the person.",
      },
      {
        en: "I totally agree with …",
        vi: "Tôi hoàn toàn đồng ý với …",
        ipa: "/aɪ ˈtəʊtəli əˈɡriː wɪð/",
        example: "I totally agree with what you just said.",
      },
      {
        en: "I'm not so sure about that.",
        vi: "Tôi không chắc về điều đó lắm.",
        ipa: "/aɪm nɒt səʊ ʃʊər/",
        example: "I'm not so sure about that — can you explain more?",
      },
      {
        en: "The main reason is …",
        vi: "Lý do chính là …",
        ipa: "/ðə meɪn ˈriːzn ɪz/",
        example: "I prefer trains. The main reason is they're more comfortable.",
      },
      {
        en: "For example, …",
        vi: "Ví dụ như …",
        ipa: "/fər ɪɡˈzɑːmpl/",
        example: "Exercise helps a lot. For example, I sleep better now.",
      },
      {
        en: "It depends on …",
        vi: "Còn tùy vào …",
        ipa: "/ɪt dɪˈpɛndz ɒn/",
        example: "It depends on how you look at it.",
      },
      {
        en: "On the other hand, …",
        vi: "Mặt khác, …",
        ipa: "/ɒn ðə ˈʌðər hænd/",
        example: "It's cheap, but on the other hand, the quality is poor.",
      },
      {
        en: "I'd say that …",
        vi: "Tôi cho rằng …",
        ipa: "/aɪd seɪ ðæt/",
        example: "I'd say that practice matters more than talent.",
      },
    ],
  },
  "think-in-english": {
    slug: "think-in-english",
    title: "Suy nghĩ bằng tiếng Anh",
    cefr: "B1+",
    intro:
      "Giảm 'dịch trong đầu' bằng cách độc thoại nội tâm tiếng Anh trong sinh hoạt hằng ngày — bước đệm để nói trôi chảy.",
    tip: "Mỗi ngày chọn 5 phút 'chỉ nghĩ bằng tiếng Anh': tả việc đang làm, sắp làm và cảm xúc của bạn — không dịch.",
    phrases: [
      {
        en: "Right now I'm …ing.",
        vi: "Ngay bây giờ tôi đang … (tự tả việc đang làm)",
        ipa: "/raɪt naʊ aɪm/",
        example: "Right now I'm making coffee and thinking about my day.",
      },
      {
        en: "Next, I need to …",
        vi: "Tiếp theo, tôi cần …",
        ipa: "/nɛkst aɪ niːd tə/",
        example: "Next, I need to reply to that email.",
      },
      {
        en: "I wonder if …",
        vi: "Không biết liệu …",
        ipa: "/aɪ ˈwʌndər ɪf/",
        example: "I wonder if it's going to rain this afternoon.",
      },
      {
        en: "How do I say … in English?",
        vi: "… nói tiếng Anh thế nào nhỉ?",
        ipa: "/haʊ də aɪ seɪ/",
        example: "How do I say this feeling in English? Maybe 'overwhelmed'.",
      },
      {
        en: "Let me describe it another way.",
        vi: "Để tôi diễn đạt cách khác.",
        ipa: "/lɛt miː dɪˈskraɪb ɪt əˈnʌðər weɪ/",
        example: "I don't know that word — let me describe it another way.",
      },
      {
        en: "On the whole, I feel …",
        vi: "Nhìn chung, tôi cảm thấy …",
        ipa: "/ɒn ðə həʊl aɪ fiːl/",
        example: "On the whole, I feel happy with my progress today.",
      },
      {
        en: "What's the word for …?",
        vi: "Từ chỉ … là gì nhỉ?",
        ipa: "/wɒts ðə wɜːd fɔː/",
        example: "What's the word for this? It starts with 's'.",
      },
      {
        en: "It reminds me of …",
        vi: "Nó làm tôi nhớ đến …",
        ipa: "/ɪt rɪˈmaɪndz miː ɒv/",
        example: "This song reminds me of my hometown.",
      },
      {
        en: "I'd better … now.",
        vi: "Tôi nên … bây giờ thì hơn.",
        ipa: "/aɪd ˈbɛtər … naʊ/",
        example: "It's late — I'd better go to bed now.",
      },
    ],
  },
  "clothes-appearance": {
    slug: "clothes-appearance",
    title: "Quần áo & ngoại hình",
    cefr: "A1",
    intro: "Mô tả trang phục và ngoại hình của bản thân và người khác.",
    tip: "Tập tả cách ăn mặc của người quanh bạn bằng 2–3 câu mỗi ngày.",
    phrases: [
      { en: "He's wearing a blue shirt.", vi: "Anh ấy đang mặc áo sơ mi xanh.", ipa: "/hiːz ˈweərɪŋ/", example: "Look, he's wearing a blue shirt today." },
      { en: "She has long black hair.", vi: "Cô ấy có mái tóc đen dài.", ipa: "/ʃiː hæz lɒŋ/", example: "My teacher has long black hair." },
      { en: "I usually wear jeans.", vi: "Tôi thường mặc quần jean.", ipa: "/aɪ ˈjuːʒuəli weər/", example: "At weekends I usually wear jeans and a T-shirt." },
      { en: "It doesn't fit me.", vi: "Nó không vừa với tôi.", ipa: "/ɪt ˈdʌznt fɪt/", example: "This jacket is nice but it doesn't fit me." },
      { en: "What size are you?", vi: "Bạn mặc cỡ nào?", ipa: "/wɒt saɪz ɑːr juː/", example: "What size are you — medium or large?" },
      { en: "He looks young.", vi: "Trông anh ấy trẻ.", ipa: "/hiː lʊks jʌŋ/", example: "He's forty but he looks young." },
      { en: "Can I try this on?", vi: "Tôi thử cái này được không?", ipa: "/kæn aɪ traɪ ðɪs ɒn/", example: "Excuse me, can I try this on?" },
      { en: "It suits you.", vi: "Nó hợp với bạn.", ipa: "/ɪt suːts juː/", example: "That colour really suits you." },
    ],
  },
  "house-home": {
    slug: "house-home",
    title: "Nhà cửa & đồ đạc",
    cefr: "A1",
    intro: "Nói về nơi ở, các phòng và đồ đạc trong nhà.",
    tip: "Đi quanh nhà và gọi tên mọi thứ bằng tiếng Anh.",
    phrases: [
      { en: "I live in a small flat.", vi: "Tôi sống trong căn hộ nhỏ.", ipa: "/aɪ lɪv ɪn ə smɔːl flæt/", example: "I live in a small flat near the city centre." },
      { en: "There is a sofa in the living room.", vi: "Có một ghế sofa trong phòng khách.", ipa: "/ðeər ɪz ə ˈsəʊfə/", example: "There is a big sofa in the living room." },
      { en: "My room is on the second floor.", vi: "Phòng tôi ở tầng hai.", ipa: "/maɪ ruːm/", example: "My room is on the second floor, next to the bathroom." },
      { en: "We have a small garden.", vi: "Chúng tôi có một khu vườn nhỏ.", ipa: "/wiː hæv ə ˈɡɑːdn/", example: "We have a small garden behind the house." },
      { en: "Could you turn on the light?", vi: "Bạn bật đèn giúp được không?", ipa: "/tɜːn ɒn ðə laɪt/", example: "It's dark — could you turn on the light?" },
      { en: "The kitchen is next to the…", vi: "Bếp ở cạnh…", ipa: "/ðə ˈkɪtʃɪn/", example: "The kitchen is next to the dining room." },
      { en: "I need to tidy my room.", vi: "Tôi cần dọn phòng.", ipa: "/ˈtaɪdi maɪ ruːm/", example: "It's messy — I need to tidy my room." },
      { en: "Make yourself at home.", vi: "Cứ tự nhiên như ở nhà.", ipa: "/meɪk jɔːˈsɛlf ət həʊm/", example: "Come in, make yourself at home!" },
    ],
  },
  "shopping-money": {
    slug: "shopping-money",
    title: "Mua sắm & trả giá",
    cefr: "A2",
    intro: "Mua đồ, hỏi giá, trả giá và thanh toán trong tình huống mua sắm.",
    tip: "Đóng vai khách & người bán; tập hỏi giá và mặc cả thành tiếng.",
    phrases: [
      { en: "How much does it cost?", vi: "Cái này giá bao nhiêu?", ipa: "/haʊ mʌtʃ dʌz ɪt kɒst/", example: "Excuse me, how much does this bag cost?" },
      { en: "That's too expensive.", vi: "Đắt quá.", ipa: "/ðæts tuː ɪkˈspɛnsɪv/", example: "Hmm, that's too expensive for me." },
      { en: "Can you give me a discount?", vi: "Bạn giảm giá được không?", ipa: "/ə ˈdɪskaʊnt/", example: "I'll buy two — can you give me a discount?" },
      { en: "Do you take card?", vi: "Có nhận thẻ không?", ipa: "/duː juː teɪk kɑːd/", example: "Do you take card or only cash?" },
      { en: "I'm just looking, thanks.", vi: "Tôi chỉ xem thôi, cảm ơn.", ipa: "/aɪm dʒʌst ˈlʊkɪŋ/", example: "Can I help you? — I'm just looking, thanks." },
      { en: "Have you got this in…?", vi: "Có cái này màu/cỡ … không?", ipa: "/hæv juː ɡɒt ðɪs ɪn/", example: "Have you got this in a smaller size?" },
      { en: "Here's your change.", vi: "Đây là tiền thừa của bạn.", ipa: "/hɪəz jɔː tʃeɪndʒ/", example: "That's ten dollars. Here's your change." },
      { en: "It's on sale.", vi: "Nó đang giảm giá.", ipa: "/ɪts ɒn seɪl/", example: "You should buy it now — it's on sale." },
    ],
  },
  "feelings-emotions": {
    slug: "feelings-emotions",
    title: "Cảm xúc & tâm trạng",
    cefr: "A2",
    intro: "Nói về cảm xúc của mình và hỏi thăm cảm xúc người khác.",
    tip: "Mỗi tối, tả tâm trạng trong ngày bằng 2–3 câu tiếng Anh.",
    phrases: [
      { en: "I'm feeling a bit tired.", vi: "Tôi thấy hơi mệt.", ipa: "/aɪm ˈfiːlɪŋ ə bɪt ˈtaɪəd/", example: "I'm feeling a bit tired after work." },
      { en: "I'm really excited about…", vi: "Tôi rất hào hứng về…", ipa: "/ɪkˈsaɪtɪd əˈbaʊt/", example: "I'm really excited about the trip." },
      { en: "That makes me happy.", vi: "Điều đó làm tôi vui.", ipa: "/ðæt meɪks miː ˈhæpi/", example: "Seeing my friends makes me happy." },
      { en: "I'm worried about…", vi: "Tôi lo về…", ipa: "/aɪm ˈwʌrid əˈbaʊt/", example: "I'm a bit worried about the exam." },
      { en: "Are you okay?", vi: "Bạn ổn chứ?", ipa: "/ɑːr juː əʊˈkeɪ/", example: "You look sad. Are you okay?" },
      { en: "Don't worry about it.", vi: "Đừng lo về chuyện đó.", ipa: "/dəʊnt ˈwʌri/", example: "It's fine, don't worry about it." },
      { en: "I feel much better now.", vi: "Giờ tôi thấy khá hơn nhiều.", ipa: "/aɪ fiːl mʌtʃ ˈbɛtə/", example: "Thanks for listening — I feel much better now." },
      { en: "It was such a relief.", vi: "Thật là nhẹ cả người.", ipa: "/sʌtʃ ə rɪˈliːf/", example: "When I passed, it was such a relief." },
    ],
  },
  "making-plans": {
    slug: "making-plans",
    title: "Hẹn hò & rủ rê",
    cefr: "A2",
    intro: "Rủ rê, nhận lời, từ chối lịch sự và hẹn thời gian gặp.",
    tip: "Tập cả ba: rủ, đồng ý và từ chối khéo — để hội thoại linh hoạt.",
    phrases: [
      { en: "Do you want to hang out?", vi: "Bạn muốn đi chơi không?", ipa: "/hæŋ aʊt/", example: "Do you want to hang out this weekend?" },
      { en: "How about Saturday?", vi: "Thứ Bảy thì sao?", ipa: "/haʊ əˈbaʊt/", example: "Let's meet up. How about Saturday?" },
      { en: "Sounds great!", vi: "Nghe hay đấy!", ipa: "/saʊndz ɡreɪt/", example: "A movie? Sounds great!" },
      { en: "I'd love to, but…", vi: "Tôi rất muốn, nhưng…", ipa: "/aɪd lʌv tuː bʌt/", example: "I'd love to, but I'm busy that day." },
      { en: "Let's meet at…", vi: "Hẹn gặp ở… lúc…", ipa: "/lɛts miːt æt/", example: "Let's meet at the café at six." },
      { en: "Can we make it later?", vi: "Dời muộn hơn được không?", ipa: "/meɪk ɪt ˈleɪtə/", example: "Can we make it a bit later, say seven?" },
      { en: "I'll let you know.", vi: "Tôi sẽ báo bạn sau.", ipa: "/aɪl lɛt juː nəʊ/", example: "I'm not sure yet — I'll let you know." },
      { en: "See you then!", vi: "Hẹn gặp lúc đó nhé!", ipa: "/siː juː ðɛn/", example: "Okay, see you then!" },
    ],
  },
  "technology-phone": {
    slug: "technology-phone",
    title: "Công nghệ & điện thoại",
    cefr: "B1",
    intro: "Nói về thiết bị, ứng dụng và xử lý sự cố công nghệ thường gặp.",
    tip: "Khi dùng máy tính/điện thoại, thử mô tả thao tác bằng tiếng Anh.",
    phrases: [
      { en: "My phone keeps freezing.", vi: "Điện thoại tôi cứ bị treo.", ipa: "/kiːps ˈfriːzɪŋ/", example: "I need a new phone — mine keeps freezing." },
      { en: "Could you send me the link?", vi: "Gửi mình cái link nhé?", ipa: "/sɛnd miː ðə lɪŋk/", example: "That looks useful — could you send me the link?" },
      { en: "I'll download the app.", vi: "Tôi sẽ tải ứng dụng.", ipa: "/ˌdaʊnˈləʊd ði æp/", example: "To book a ride, I'll download the app." },
      { en: "The battery is almost dead.", vi: "Pin sắp cạn rồi.", ipa: "/ðə ˈbætəri/", example: "Can I charge my phone? The battery is almost dead." },
      { en: "I forgot my password.", vi: "Tôi quên mật khẩu.", ipa: "/fəˈɡɒt maɪ ˈpɑːswɜːd/", example: "I can't log in — I forgot my password." },
      { en: "Try turning it off and on.", vi: "Thử tắt rồi bật lại.", ipa: "/tɜːnɪŋ ɪt ɒf/", example: "It's not working? Try turning it off and on again." },
      { en: "Is there free wifi here?", vi: "Ở đây có wifi miễn phí không?", ipa: "/friː ˈwaɪfaɪ/", example: "Excuse me, is there free wifi here?" },
      { en: "I'll back up my files.", vi: "Tôi sẽ sao lưu dữ liệu.", ipa: "/bæk ʌp maɪ faɪlz/", example: "Before the update, I'll back up my files." },
    ],
  },
  "work-office": {
    slug: "work-office",
    title: "Công việc & văn phòng",
    cefr: "B1",
    intro: "Giao tiếp nơi làm việc: họp, email, deadline và phối hợp đồng nghiệp.",
    tip: "Tập diễn đạt công việc bạn làm và yêu cầu hỗ trợ một cách lịch sự.",
    phrases: [
      { en: "I'm in charge of…", vi: "Tôi phụ trách…", ipa: "/ɪn tʃɑːdʒ ɒv/", example: "I'm in charge of the marketing team." },
      { en: "Let's schedule a meeting.", vi: "Hãy sắp một cuộc họp.", ipa: "/ˈʃɛdjuːl ə ˈmiːtɪŋ/", example: "Let's schedule a meeting for Monday morning." },
      { en: "Can you send me the report?", vi: "Gửi mình báo cáo nhé?", ipa: "/ðə rɪˈpɔːt/", example: "Can you send me the report by tomorrow?" },
      { en: "I'll get back to you.", vi: "Tôi sẽ phản hồi lại bạn.", ipa: "/ɡɛt bæk tuː juː/", example: "Let me check and I'll get back to you." },
      { en: "We're behind schedule.", vi: "Chúng ta đang trễ tiến độ.", ipa: "/bɪˈhaɪnd ˈʃɛdjuːl/", example: "We're a bit behind schedule on this project." },
      { en: "Could you give me a hand?", vi: "Bạn giúp tôi một tay được không?", ipa: "/ɡɪv miː ə hænd/", example: "This is heavy — could you give me a hand?" },
      { en: "The deadline is on Friday.", vi: "Hạn chót là thứ Sáu.", ipa: "/ðə ˈdɛdlaɪn/", example: "Remember, the deadline is on Friday." },
      { en: "I'm taking a day off.", vi: "Tôi xin nghỉ một ngày.", ipa: "/ə deɪ ɒf/", example: "I'm taking a day off tomorrow." },
    ],
  },
  "environment-nature": {
    slug: "environment-nature",
    title: "Môi trường & thiên nhiên",
    cefr: "B1",
    intro: "Nói về môi trường, thói quen xanh và các vấn đề thiên nhiên.",
    tip: "Chọn một vấn đề môi trường và nêu ý kiến của bạn trong 30 giây.",
    phrases: [
      { en: "We should recycle more.", vi: "Chúng ta nên tái chế nhiều hơn.", ipa: "/wiː ʃʊd ˌriːˈsaɪkl/", example: "To help the planet, we should recycle more." },
      { en: "Climate change is a big problem.", vi: "Biến đổi khí hậu là vấn đề lớn.", ipa: "/ˈklaɪmət tʃeɪndʒ/", example: "In my opinion, climate change is a big problem." },
      { en: "I try to save energy.", vi: "Tôi cố gắng tiết kiệm năng lượng.", ipa: "/seɪv ˈɛnədʒi/", example: "I turn off the lights to save energy." },
      { en: "We use too much plastic.", vi: "Chúng ta dùng quá nhiều nhựa.", ipa: "/tuː mʌtʃ ˈplæstɪk/", example: "These days we use too much plastic." },
      { en: "It's better to take public transport.", vi: "Tốt hơn là dùng phương tiện công cộng.", ipa: "/ˈpʌblɪk ˈtrænspɔːt/", example: "It's better to take public transport than to drive." },
      { en: "We can plant more trees.", vi: "Chúng ta có thể trồng thêm cây.", ipa: "/plɑːnt mɔː triːz/", example: "To clean the air, we can plant more trees." },
      { en: "The air is heavily polluted.", vi: "Không khí ô nhiễm nặng.", ipa: "/pəˈluːtɪd/", example: "In big cities, the air is heavily polluted." },
      { en: "Every little helps.", vi: "Góp gió thành bão / việc nhỏ cũng giúp ích.", ipa: "/ˈɛvri ˈlɪtl hɛlps/", example: "Bring your own bag — every little helps." },
    ],
  },
  "small-talk": {
    slug: "small-talk",
    title: "Nói chuyện xã giao",
    cefr: "B1+",
    intro: "Bắt chuyện và duy trì hội thoại nhẹ nhàng với người mới quen.",
    tip: "Học vài 'câu mồi' để mở và giữ hội thoại; tránh im lặng gượng gạo.",
    phrases: [
      { en: "How's it going?", vi: "Dạo này sao rồi?", ipa: "/haʊz ɪt ˈɡəʊɪŋ/", example: "Hey! How's it going?" },
      { en: "What have you been up to?", vi: "Dạo này bạn làm gì?", ipa: "/wɒt hæv juː bɪn ʌp tuː/", example: "Long time no see! What have you been up to?" },
      { en: "By the way, …", vi: "Nhân tiện, …", ipa: "/baɪ ðə weɪ/", example: "By the way, did you see the game last night?" },
      { en: "That reminds me of…", vi: "Điều đó làm tôi nhớ đến…", ipa: "/rɪˈmaɪndz miː ɒv/", example: "That reminds me of my trip last year." },
      { en: "Speaking of…", vi: "Nói đến… thì…", ipa: "/ˈspiːkɪŋ ɒv/", example: "Speaking of food, have you tried that new place?" },
      { en: "I know what you mean.", vi: "Tôi hiểu ý bạn.", ipa: "/aɪ nəʊ wɒt juː miːn/", example: "Mondays are hard — I know what you mean." },
      { en: "Anyway, I should get going.", vi: "Dù sao thì, tôi phải đi đây.", ipa: "/ˈɛniweɪ/", example: "Anyway, I should get going. Nice talking to you!" },
      { en: "Let's catch up soon.", vi: "Hôm nào gặp lại nhé.", ipa: "/kætʃ ʌp suːn/", example: "It was great seeing you — let's catch up soon." },
    ],
  },

  // ───────────────────────── B1 · NGỮ PHÁP CỐT LÕI ─────────────────────────
  "present-perfect-continuous": {
    slug: "present-perfect-continuous",
    title: "Hiện tại hoàn thành tiếp diễn",
    cefr: "B1",
    intro: "Nói về việc đã làm liên tục đến hiện tại hoặc vừa mới dừng (have/has been + V-ing).",
    tip: "Nhấn vào 'been + V-ing'. Dùng khi muốn nói 'đã … được một thời gian rồi'.",
    phrases: [
      { en: "I've been learning English.", vi: "Tôi đã học tiếng Anh (một thời gian rồi).", ipa: "/aɪv bɪn ˈlɜːnɪŋ ˈɪŋɡlɪʃ/", example: "I've been learning English for two years." },
      { en: "How long have you been…?", vi: "Bạn đã … bao lâu rồi?", ipa: "/haʊ lɒŋ hæv juː bɪn/", example: "How long have you been waiting here?" },
      { en: "She's been working all day.", vi: "Cô ấy làm việc cả ngày nay.", ipa: "/ʃiːz bɪn ˈwɜːkɪŋ ɔːl deɪ/", example: "She's tired because she's been working all day." },
      { en: "It's been raining.", vi: "Trời mưa suốt nãy giờ.", ipa: "/ɪts bɪn ˈreɪnɪŋ/", example: "The road is wet — it's been raining." },
      { en: "I've been thinking about it.", vi: "Tôi đã suy nghĩ về việc đó.", ipa: "/aɪv bɪn ˈθɪŋkɪŋ əˈbaʊt ɪt/", example: "I've been thinking about it, and I agree with you." },
      { en: "We've been waiting for an hour.", vi: "Chúng tôi đợi cả tiếng rồi.", ipa: "/wiːv bɪn ˈweɪtɪŋ fər ən ˈaʊə/", example: "We've been waiting for an hour. Where are you?" },
      { en: "He's been feeling tired lately.", vi: "Dạo này anh ấy thấy mệt.", ipa: "/hiːz bɪn ˈfiːlɪŋ ˈtaɪəd ˈleɪtli/", example: "He's been feeling tired lately, so he's resting." },
      { en: "They've been living here since 2020.", vi: "Họ sống ở đây từ năm 2020.", ipa: "/ðeɪv bɪn ˈlɪvɪŋ hɪə sɪns/", example: "They've been living here since 2020." },
      { en: "What have you been up to?", vi: "Dạo này bạn làm gì?", ipa: "/wɒt hæv juː bɪn ʌp tuː/", example: "Hey! What have you been up to recently?" },
    ],
  },

  "second-conditional": {
    slug: "second-conditional",
    title: "Câu điều kiện loại 2",
    cefr: "B1",
    intro: "Nói về tình huống giả định, không có thật ở hiện tại (If + quá khứ, would + V).",
    tip: "Học nguyên khối 'If I were you, I'd…' và 'What would you do if…?' để bật ra ngay.",
    phrases: [
      { en: "If I were you, I'd…", vi: "Nếu là bạn, tôi sẽ…", ipa: "/ɪf aɪ wɜː juː aɪd/", example: "If I were you, I'd take the job." },
      { en: "What would you do if…?", vi: "Bạn sẽ làm gì nếu…?", ipa: "/wɒt wʊd juː duː ɪf/", example: "What would you do if you won the lottery?" },
      { en: "If I had more time, I would…", vi: "Nếu có thêm thời gian, tôi sẽ…", ipa: "/ɪf aɪ hæd mɔː taɪm aɪ wʊd/", example: "If I had more time, I would travel more." },
      { en: "I wouldn't do that.", vi: "Tôi sẽ không làm vậy.", ipa: "/aɪ ˈwʊdnt duː ðæt/", example: "I wouldn't do that if I were you." },
      { en: "If I could, I would help.", vi: "Nếu có thể, tôi sẽ giúp.", ipa: "/ɪf aɪ kʊd aɪ wʊd help/", example: "If I could, I would help you move." },
      { en: "It would be great if…", vi: "Sẽ tuyệt nếu…", ipa: "/ɪt wʊd biː ɡreɪt ɪf/", example: "It would be great if you could come." },
      { en: "Where would you go if…?", vi: "Bạn sẽ đi đâu nếu…?", ipa: "/weə wʊd juː ɡəʊ ɪf/", example: "Where would you go if you had a free week?" },
      { en: "If it weren't so expensive…", vi: "Nếu nó không quá đắt…", ipa: "/ɪf ɪt ˈwɜːnt səʊ ɪkˈspensɪv/", example: "If it weren't so expensive, I'd buy it." },
      { en: "I'd probably say no.", vi: "Tôi chắc sẽ từ chối.", ipa: "/aɪd ˈprɒbəbli seɪ nəʊ/", example: "If they asked me, I'd probably say no." },
    ],
  },

  "modals-deduction": {
    slug: "modals-deduction",
    title: "Suy đoán & khả năng",
    cefr: "B1",
    intro: "Phỏng đoán mức độ chắc chắn: must (chắc chắn), might/may/could (có thể), can't (không thể).",
    tip: "must = gần như chắc; might/could = có thể; can't = chắc chắn không. Dựa vào bằng chứng để chọn.",
    phrases: [
      { en: "It must be true.", vi: "Chắc chắn là thật.", ipa: "/ɪt mʌst biː truː/", example: "She's smiling — it must be good news." },
      { en: "He might be late.", vi: "Anh ấy có thể đến muộn.", ipa: "/hiː maɪt biː leɪt/", example: "He might be late because of the traffic." },
      { en: "That can't be right.", vi: "Không thể đúng được.", ipa: "/ðæt kɑːnt biː raɪt/", example: "That can't be right — let's check again." },
      { en: "She must be tired.", vi: "Chắc cô ấy mệt.", ipa: "/ʃiː mʌst biː ˈtaɪəd/", example: "She's worked all day; she must be tired." },
      { en: "It might rain later.", vi: "Có thể lát nữa trời mưa.", ipa: "/ɪt maɪt reɪn ˈleɪtə/", example: "Take an umbrella — it might rain later." },
      { en: "You must be joking.", vi: "Chắc bạn đùa.", ipa: "/juː mʌst biː ˈdʒəʊkɪŋ/", example: "You must be joking! That's wonderful." },
      { en: "They could be at home.", vi: "Họ có thể đang ở nhà.", ipa: "/ðeɪ kʊd biː ət həʊm/", example: "Nobody's answering; they could be at home." },
      { en: "It may not work.", vi: "Có thể không được.", ipa: "/ɪt meɪ nɒt wɜːk/", example: "It's an old phone, so it may not work." },
      { en: "He can't be serious.", vi: "Anh ấy không thể nghiêm túc.", ipa: "/hiː kɑːnt biː ˈsɪəriəs/", example: "He can't be serious about quitting his job." },
    ],
  },

  "passive-simple": {
    slug: "passive-simple",
    title: "Câu bị động cơ bản",
    cefr: "B1",
    intro: "Nói về việc xảy ra với chủ thể khi không cần nêu ai làm (be + V3/V-ed).",
    tip: "Dùng bị động khi 'ai làm' không quan trọng hoặc không rõ. Chú ý chia 'be' đúng thì.",
    phrases: [
      { en: "It is made of…", vi: "Nó được làm bằng…", ipa: "/ɪt ɪz meɪd ɒv/", example: "This table is made of wood." },
      { en: "English is spoken here.", vi: "Ở đây nói tiếng Anh.", ipa: "/ˈɪŋɡlɪʃ ɪz ˈspəʊkən hɪə/", example: "English is spoken in many countries." },
      { en: "It was built in…", vi: "Nó được xây vào…", ipa: "/ɪt wɒz bɪlt ɪn/", example: "This bridge was built in 1995." },
      { en: "It's called…", vi: "Nó được gọi là…", ipa: "/ɪts kɔːld/", example: "This dish is called 'phở'." },
      { en: "The room is cleaned every day.", vi: "Phòng được dọn mỗi ngày.", ipa: "/ðə ruːm ɪz kliːnd ˈevri deɪ/", example: "Don't worry — the room is cleaned every day." },
      { en: "My phone was stolen.", vi: "Điện thoại tôi bị trộm.", ipa: "/maɪ fəʊn wɒz ˈstəʊlən/", example: "My phone was stolen on the bus yesterday." },
      { en: "It is used for…", vi: "Nó được dùng để…", ipa: "/ɪt ɪz juːzd fɔː/", example: "This app is used for learning English." },
      { en: "The email was sent yesterday.", vi: "Email được gửi hôm qua.", ipa: "/ðə ˈiːmeɪl wɒz sent ˈjestədeɪ/", example: "The email was sent yesterday afternoon." },
      { en: "It was written by…", vi: "Nó được viết bởi…", ipa: "/ɪt wɒz ˈrɪtn baɪ/", example: "This song was written by a young artist." },
    ],
  },

  "reported-speech": {
    slug: "reported-speech",
    title: "Câu tường thuật",
    cefr: "B1",
    intro: "Thuật lại lời người khác nói (say/tell/ask) — lùi thì một bậc về quá khứ.",
    tip: "say + (that) … ; tell + ai + … ; ask + if/wh-. Hiện tại → quá khứ, will → would.",
    phrases: [
      { en: "He said (that) he was busy.", vi: "Anh ấy nói anh ấy bận.", ipa: "/hiː sed ðæt hiː wɒz ˈbɪzi/", example: "He said that he was busy that day." },
      { en: "She told me to wait.", vi: "Cô ấy bảo tôi chờ.", ipa: "/ʃiː təʊld miː tə weɪt/", example: "She told me to wait outside." },
      { en: "They said they would come.", vi: "Họ nói sẽ đến.", ipa: "/ðeɪ sed ðeɪ wʊd kʌm/", example: "They said they would come later." },
      { en: "He asked if I was okay.", vi: "Anh ấy hỏi tôi có ổn không.", ipa: "/hiː ɑːskt ɪf aɪ wɒz əʊˈkeɪ/", example: "He asked if I was okay after the trip." },
      { en: "I told him I didn't know.", vi: "Tôi bảo anh ấy tôi không biết.", ipa: "/aɪ təʊld hɪm aɪ ˈdɪdnt nəʊ/", example: "I told him I didn't know the answer." },
      { en: "She asked where I lived.", vi: "Cô ấy hỏi tôi sống ở đâu.", ipa: "/ʃiː ɑːskt weər aɪ lɪvd/", example: "She asked where I lived now." },
      { en: "He said he had finished.", vi: "Anh ấy nói đã làm xong.", ipa: "/hiː sed hiː hæd ˈfɪnɪʃt/", example: "He said he had finished the report." },
      { en: "They told us not to worry.", vi: "Họ bảo chúng tôi đừng lo.", ipa: "/ðeɪ təʊld ʌs nɒt tə ˈwʌri/", example: "They told us not to worry about the delay." },
      { en: "She said she would call back.", vi: "Cô ấy nói sẽ gọi lại.", ipa: "/ʃiː sed ʃiː wʊd kɔːl bæk/", example: "She said she would call back in an hour." },
    ],
  },

  // ───────────────────────── B2 · NGỮ PHÁP NÂNG CAO ─────────────────────────
  "narrative-tenses": {
    slug: "narrative-tenses",
    title: "Thì kể chuyện",
    cefr: "B2",
    intro: "Kể chuyện mạch lạc bằng cách phối hợp quá khứ đơn, quá khứ tiếp diễn và quá khứ hoàn thành (việc xảy ra trước/sau, bối cảnh & ngắt quãng).",
    tip: "Quá khứ tiếp diễn = bối cảnh đang diễn ra; quá khứ đơn = việc xen vào; quá khứ hoàn thành = việc xảy ra TRƯỚC đó.",
    phrases: [
      { en: "I was walking home when…", vi: "Tôi đang đi bộ về thì…", ipa: "/aɪ wɒz ˈwɔːkɪŋ həʊm wen/", example: "I was walking home when it started to rain." },
      { en: "By the time we arrived, …", vi: "Đến lúc chúng tôi tới thì…", ipa: "/baɪ ðə taɪm wiː əˈraɪvd/", example: "By the time we arrived, the show had started." },
      { en: "She had already left.", vi: "Cô ấy đã rời đi rồi.", ipa: "/ʃiː hæd ɔːlˈredi left/", example: "When I called, she had already left." },
      { en: "It had been raining all day.", vi: "Trời đã mưa cả ngày.", ipa: "/ɪt hæd bɪn ˈreɪnɪŋ ɔːl deɪ/", example: "The ground was wet — it had been raining all day." },
      { en: "While I was cooking, …", vi: "Trong lúc tôi đang nấu ăn,…", ipa: "/waɪl aɪ wɒz ˈkʊkɪŋ/", example: "While I was cooking, the phone rang." },
      { en: "As soon as I saw him, …", vi: "Ngay khi tôi thấy anh ấy,…", ipa: "/əz suːn əz aɪ sɔː hɪm/", example: "As soon as I saw him, I knew something was wrong." },
      { en: "We had been waiting for hours.", vi: "Chúng tôi đã đợi hàng giờ.", ipa: "/wiː hæd bɪn ˈweɪtɪŋ fər ˈaʊəz/", example: "We had been waiting for hours before the bus came." },
      { en: "Suddenly, everything went quiet.", vi: "Đột nhiên, mọi thứ im bặt.", ipa: "/ˈsʌdnli ˈevriθɪŋ went ˈkwaɪət/", example: "Suddenly, everything went quiet." },
      { en: "It turned out (that)…", vi: "Hóa ra là…", ipa: "/ɪt tɜːnd aʊt ðæt/", example: "It turned out that he had known all along." },
    ],
  },

  "third-conditional": {
    slug: "third-conditional",
    title: "Câu điều kiện loại 3 & hỗn hợp",
    cefr: "B2",
    intro: "Nói về điều trái với quá khứ (hối tiếc, giả định đã khác): If + had + V3, would have + V3. Câu hỗn hợp nối quá khứ với hiện tại.",
    tip: "Loại 3: If + quá khứ hoàn thành → would have + V3. Hỗn hợp: điều kiện quá khứ → kết quả hiện tại (would + V).",
    phrases: [
      { en: "If I had known, I would have…", vi: "Nếu tôi biết, tôi đã…", ipa: "/ɪf aɪ həd nəʊn aɪ wʊd həv/", example: "If I had known, I would have told you." },
      { en: "I wouldn't have done that.", vi: "Tôi đã không làm thế (nếu…).", ipa: "/aɪ ˈwʊdnt həv dʌn ðæt/", example: "I wouldn't have said anything if I'd known." },
      { en: "She would have passed if…", vi: "Cô ấy đã đậu nếu…", ipa: "/ʃiː wʊd həv pɑːst ɪf/", example: "She would have passed if she had studied." },
      { en: "We could have won if…", vi: "Chúng tôi đã có thể thắng nếu…", ipa: "/wiː kʊd həv wʌn ɪf/", example: "We could have won if we'd played better." },
      { en: "If it hadn't rained, …", vi: "Nếu trời không mưa thì…", ipa: "/ɪf ɪt ˈhædnt reɪnd/", example: "If it hadn't rained, we would have gone out." },
      { en: "You should have told me.", vi: "Lẽ ra bạn nên nói với tôi.", ipa: "/juː ʃʊd həv təʊld miː/", example: "You should have told me earlier." },
      { en: "What would you have done?", vi: "Bạn sẽ đã làm gì (lúc đó)?", ipa: "/wɒt wʊd juː həv dʌn/", example: "What would you have done in my place?" },
      { en: "If I'd been there, I would have helped.", vi: "Nếu tôi ở đó, tôi đã giúp.", ipa: "/ɪf aɪd bɪn ðeə aɪ wʊd həv helpt/", example: "If I'd been there, I would have helped you." },
      { en: "If I had saved more, I'd be richer now.", vi: "Nếu tôi tiết kiệm hơn, giờ đã giàu hơn. (hỗn hợp)", ipa: "/ɪf aɪ həd seɪvd mɔː aɪd biː ˈrɪtʃə naʊ/", example: "If I had saved more, I'd be richer now." },
    ],
  },

  "relative-clauses": {
    slug: "relative-clauses",
    title: "Mệnh đề quan hệ",
    cefr: "B2",
    intro: "Nối câu và bổ sung thông tin cho danh từ bằng who/which/that/whose/where/when — nói câu dài, mạch lạc, tự nhiên hơn.",
    tip: "who = người · which = vật · that = cả hai (mệnh đề xác định) · whose = sở hữu · where = nơi chốn. Có thể lược 'that/which' khi nó là tân ngữ.",
    phrases: [
      { en: "the person who…", vi: "người mà…", ipa: "/ðə ˈpɜːsn huː/", example: "She's the person who helped me." },
      { en: "the thing that…", vi: "điều/thứ mà…", ipa: "/ðə θɪŋ ðæt/", example: "That's the thing that worries me." },
      { en: "the place where…", vi: "nơi mà…", ipa: "/ðə pleɪs weə/", example: "This is the place where we first met." },
      { en: "the reason why…", vi: "lý do mà…", ipa: "/ðə ˈriːzn waɪ/", example: "Tell me the reason why you left." },
      { en: "…, which is…", vi: "…, điều mà… (bổ sung)", ipa: "/wɪtʃ ɪz/", example: "He arrived late, which annoyed everyone." },
      { en: "the man whose…", vi: "người đàn ông mà (sở hữu)…", ipa: "/ðə mæn huːz/", example: "That's the man whose car was stolen." },
      { en: "the day when…", vi: "ngày mà…", ipa: "/ðə deɪ wen/", example: "I remember the day when we first met." },
      { en: "everyone who…", vi: "tất cả những ai…", ipa: "/ˈevriwʌn huː/", example: "Everyone who came enjoyed the party." },
      { en: "the book (that) I read", vi: "cuốn sách (mà) tôi đọc", ipa: "/ðə bʊk ðæt aɪ red/", example: "The book I read last week was great." },
    ],
  },
};

export function getLesson(slug: string): LessonContent | undefined {
  return lessonContent[slug];
}
